//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public string Message1 { get; set; }
        public System.DateTime Date { get; set; }
        public int idDialog { get; set; }
        public int idUser { get; set; }
    
        public virtual Dialog Dialog { get; set; }
        public virtual User User { get; set; }
    }
}
